name: Firebase Hosting Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Export Firebase environment variables
        run: |
          export FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}
          export FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}
          export FIREBASE_DATABASE_URL=${{ secrets.FIREBASE_DATABASE_URL }}
          export FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}
          export FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}
          export FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          export FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}
          export FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }}
        shell: bash

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build --prod

      - name: Set up Firebase Authentication
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          echo $FIREBASE_SERVICE_ACCOUNT > "${{ runner.temp }}/firebase-key.json"
          export GOOGLE_APPLICATION_CREDENTIALS="${{ runner.temp }}/firebase-key.json"

      - name: Deploy to Firebase
        uses: firebase/github-action@v1
        with:
          args: deploy --only hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "${{ runner.temp }}/firebase-key.json"
